import { getSettings } from './config.js';

export interface FileInfo {
  filename: string | null;
  language?: string;
  [key: string]: unknown;
}

export interface LanguageGroup {
  language: string;
  files: FileInfo[];
}

export function filterBadExtensions(files: FileInfo[]): FileInfo[] {
  const settings = getSettings();
  let badExtensions = settings.get('bad_extensions.default') as string[];
  if (!Array.isArray(badExtensions)) {
    badExtensions = [];
  }
  if (settings.get('config.use_extra_bad_extensions')) {
    const extra = settings.get('bad_extensions.extra') as string[];
    if (Array.isArray(extra)) {
      badExtensions = badExtensions.concat(extra);
    }
  }
  return files.filter(f => f.filename !== null && isVaildFile(f.filename!, badExtensions));
}

export function isVaildFile(filename: string, badExtensions?: string[]): boolean {
  if (!filename) {
    return false;
  }
  if (!badExtensions) {
    const settings = getSettings();
    badExtensions = settings.get('bad_extensions.default') as string[];
    if (!Array.isArray(badExtensions)) {
      badExtensions = [];
    }
    if (settings.get('config.use_extra_bad_extensions')) {
      const extra = settings.get('bad_extensions.extra') as string[];
      if (Array.isArray(extra)) {
        badExtensions = badExtensions.concat(extra);
      }
    }
  }

  const autoGeneratedFilesExact = new Set([
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'composer.lock', 'Gemfile.lock',
    'poetry.lock', 'go.sum', '.terraform.lock.hcl', 'uv.lock',
    'Cargo.lock', 'Pipfile.lock', 'mix.lock', 'pubspec.lock', 'bun.lockb',
  ]);

  const autoGeneratedSuffixes = ['.min.js', '.min.css', '.js.map', '.ts.map', '.css.map'];
  const basename = filename.replace(/\\/g, '/').split('/').pop() ?? '';

  if (autoGeneratedFilesExact.has(basename)) {
    return false;
  }
  for (const suffix of autoGeneratedSuffixes) {
    if (filename.endsWith(suffix)) {
      return false;
    }
  }

  const ext = filename.split('.').pop() ?? '';
  return !badExtensions.includes(ext);
}

export function sortFilesByMainLanguages(
  languages: Record<string, number>,
  files: FileInfo[]
): LanguageGroup[] {
  const languagesSortedList = Object.entries(languages)
    .sort((a, b) => b[1] - a[1])
    .map(([k]) => k);

  const settings = getSettings();
  const languageExtensionMapOrg = settings.get('language_extension_map_org') as Record<string, string[]> ?? {};
  const languageExtensionMap: Record<string, string[]> = {};
  for (const [k, v] of Object.entries(languageExtensionMapOrg)) {
    languageExtensionMap[k.toLowerCase()] = v;
  }

  const mainExtensions: string[][] = [];
  for (const language of languagesSortedList) {
    const found = languageExtensionMap[language.toLowerCase()];
    if (found) {
      mainExtensions.push(found);
    } else {
      mainExtensions.push([]);
    }
  }

  const filesFiltered = filterBadExtensions(files);

  if (!languagesSortedList.length) {
    return [{ language: 'Other', files: [...filesFiltered] }];
  }

  const mainExtensionsFlat = mainExtensions.flat();

  const filesSorted: LanguageGroup[] = [];
  const restFiles: Record<string, FileInfo> = {};

  for (let idx = 0; idx < mainExtensions.length; idx++) {
    const extensions = mainExtensions[idx];
    const lang = languagesSortedList[idx];
    const tmp: FileInfo[] = [];
    for (const file of filesFiltered) {
      const extensionStr = '.' + (file.filename?.split('.').pop() ?? '');
      if (extensions.includes(extensionStr)) {
        tmp.push(file);
      } else {
        if (!(file.filename! in restFiles) && !mainExtensionsFlat.includes(extensionStr)) {
          restFiles[file.filename!] = file;
        }
      }
    }
    if (tmp.length > 0) {
      filesSorted.push({ language: lang, files: tmp });
    }
  }
  filesSorted.push({ language: 'Other', files: Object.values(restFiles) });
  return filesSorted;
}
